### VALORES QUE DEBERÍAS CAMBIAR ###

# CONFIGURACIONES GENERALES DEL SITIO
# title: Esto se mostrará como el nombre del sitio web en la pestaña de tu navegador.
title: Neumorfismo
# description: Esto será el contenido de la etiqueta meta HTML. Esto puede ser ignorado.
description: Sitio web personal impulsado por Jekyll
# baseurl: La subruta de tu sitio
# > pon esto en "", si renombraste el repositorio a <usuario>.github.io
baseurl: "/neumorphism"

# PÁGINA DE INICIO
# username: Esto se mostrará en la página de inicio como tu nombre.
username: Neumorfismo
# typing_text: Esto se escribirá antes de 'desplázate hacia abajo para más'.
# > pon esto como tu título laboral, por ejemplo, Desarrollador Fullstack
typing_text: Tema Jekyll
# email: Tu dirección de correo electrónico para el botón de email.
email: email@example.com
# Para cada botón social que desees mostrar, pon tu nombre de usuario o userid
# Si no usas uno de los siguientes sitios web, déjalo vacío
# > twitter_username:
github_username: longpdo
codepen_username: exampleUser
dev_username: exampleUser
linkedin_username: exampleUser
twitter_username: exampleUser

# SECCIÓN ACERCA DE MÍ
# show_aboutme_card:
# > poner esto en verdadero mostrará la sección Acerca de Mí
# > poner esto en falso omitirá la sección Acerca de Mí
show_aboutme_card: true
# about_me_title: Esto se mostrará como el título en la sección Acerca de Mí
about_me_title: Acerca de Mí
# about_me_description: Esto se mostrará debajo del título.
about_me_description: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.  Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Si te gusta este tema y quieres usarlo para ti mismo, consulta el código fuente y la documentación en <a class="highlight-link" href="https://github.com/longpdo/neumorphism" target="_blank" rel="noreferrer"> Github </a>. También puedes encontrarme en <a class="highlight-link" href="https://jamstackthemes.dev/theme/jekyll-neumorphism/" target="_blank" rel="noreferrer">JAMstack Themes</a> y en <a class="highlight-link" href="https://jekyll-themes.com/neumorphism/" target="_blank" rel="noreferrer">Jekyll Themes</a>.

# SECCIÓN DE HABILIDADES
# show_skills_card:
# > poner esto en verdadero mostrará la sección de Habilidades
# > poner esto en falso omitirá la sección de Habilidades
show_skills_card: true
# skills_title: Esto se mostrará como el título en la sección de Habilidades
skills_title: Habilidades

# SECCIÓN DE CRONOGRAMA
# show_timeline_card:
# > poner esto en verdadero mostrará la sección de Cronograma
# > poner esto en falso omitirá la sección de Cronograma
show_timeline_card: true
# timeline_title: Esto se mostrará como el título en la sección de Cronograma
timeline_title: Educación y Experiencia
# cv_download_link: El enlace donde alojas tu CV.
# > por ejemplo, si compartes tu CV en tu dropbox, añade aquí el enlace de dropbox
cv_download_link: https://example.com/

# SECCIÓN DE PROYECTOS
# show_projects_card:
# > poner esto en verdadero mostrará la sección de Proyectos
# > poner esto en falso omitirá la sección de Proyectos
show_projects_card: true
# show_projects:
# > poner esto en verdadero mostrará tus proyectos listados en _data/projects.yml
# > poner esto en falso omitirá tus proyectos listados
show_projects: true
# projects_title: Esto se mostrará como el título de tus proyectos
projects_title: Proyectos
# show_os_projects:
# > poner esto en verdadero mostrará tus proyectos públicos en github
# > poner esto en falso omitirá tus proyectos públicos en github
show_os_projects: true
# os_projects_title: Esto se mostrará como el título de tus proyectos de código abierto
os_projects_title: Proyectos de Código Abierto

# SECCIÓN DE CONTACTO
# show_contact_card:
# > poner esto en verdadero mostrará la sección de Contacto
# > poner esto en falso omitirá la sección de Contacto
show_contact_card: true
# contact_title: Esto se mostrará como el título en la sección de Contacto
contact_title: Contacto
# contact_description: Esto se mostrará debajo del título.
contact_description: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Si te gusta este tema y quieres usarlo para ti mismo, consulta el código fuente y la documentación en <a class="highlight-link" href="https://github.com/longpdo/neumorphism" target="_blank" rel="noreferrer"> Github </a>.

# METADATOS DE GITHUB
# Pon esto en tu repositorio bifurcado
# > por ejemplo <usuario>/<usuario>.github.io
repository: longpdo/neumorphism
projects:
  # sortby:
  # > pon esto en pushed, si deseas ordenar tus repositorios de github por tiempo.
  # > pon esto en stars, si deseas ordenar tus repositorios de github por estrellas.
  sort_by: pushed
  exclude:
    # archived:
    # > poner esto en verdadero, excluirá repositorios archivados
    # > poner esto en falso, también mostrará repositorios archivados
    archived: true
    # forks:
    # > poner esto en verdadero, excluirá repositorios bifurcados
    # > poner esto en falso, también mostrará repositorios bifurcados
    forks: true
    # projects: Una lista de los nombres de los repositorios que deseas excluir de la lista.
    projects:
    # - repo1-para-excluir
    # - repo2-para-excluir

# GOOGLE ANALYTICS
# Establece el id, si deseas rastrear tu sitio web con Google Analytics
# > pon esto en "", si no deseas rastrear con Google Analytics
google-analytics:
  id: "UA-158757509-2"

### FIN DE VALORES QUE DEBERÍAS CAMBIAR ###

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
